# Auto-generated by avatar_pose_pipeline bootstrap.
import inspect
try:
    from collections import namedtuple
    if not hasattr(inspect, "getargspec"):
        ArgSpec = namedtuple("ArgSpec", "args varargs keywords defaults")
        def getargspec(func):
            spec = inspect.getfullargspec(func)
            return ArgSpec(spec.args, spec.varargs, spec.varkw, spec.defaults)
        inspect.getargspec = getargspec
except Exception:
    pass

try:
    import numpy as _np
    for _name, _value in {
        "bool": bool,
        "int": int,
        "float": float,
        "complex": complex,
        "object": object,
        "str": str,
        "unicode": str,
    }.items():
        if not hasattr(_np, _name):
            setattr(_np, _name, _value)
except Exception:
    pass
